spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/oh_ho?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: ENC(YNLM1NOXKQxIITPmhPi3NwaSeTt6Yseot9wetds8b3rVWaEqwqdm9BPJlEQ0apO4)
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100
jwt:
  secretKey: ENC(V37JAtPWJmoZiv3+RDg+Gqa1opNuVQtjw8bk6MIFcH+lqJI4lIo9EpvfpuuLBOlj)
